# Generated by Django 6.0.7 on 2026-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('cclass', models.TextField(max_length=3)),
                ('fee', models.IntegerField(default=18000, null=True)),
                ('gender', models.TextField()),
            ],
        ),
    ]
